### PR TITLE
(SERVER-2758) Update jruby to 9.2.11.0

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by Magisus** [comment]
Getting test failures locally around loading openssl, want to see what happens in Travis.

**Comment by Magisus** [comment]
So this failure seems to only occur in our testing environment. Other places that work fine:
1) `require 'openssl'` in JRuby's `irb`
3) `jruby -S gem list`
2) `puppetserver gem`

The error first shows up in 9.2.10.0, which is where they [upgraded](https://github.com/jruby/jruby/pull/6077) jruby-openssl from 0.10.2 to 0.10.4.

**Comment by Magisus** [comment]
@justinstoller thoughts on this error? Or on the idea of ignoring it for the time being in favor of doing more comprehensive higher-level testing?

**Comment by justinstoller** [comment]
`[org.bouncycastle/bcpkix-jdk15on]` needs to be added to the dev dependencies (sorry took me a while to track that one down). We must have missed this repo when doing our FIPS work.

**Comment by Magisus** [comment]
Ooh, great, I'll try that, thanks!

**Comment by mwaggett** [comment]
Should we bump the Y version of jruby-utils for this change? Updating the jruby version seems bigger than a Z? ¯\_(ツ)_/¯

**Comment by Magisus** [comment]
Sure.

**Pull request merged**
